version: '3.6'

services:
  web:
    build: .
    volumes:
      - .:/code
    expose:
      - "5000"
    environment:
      - FLASK_ENV=production
    restart: always

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
    - 80:80
    depends_on:
    - web


